CREATE TABLE IF NOT EXISTS idempotency_key (
                                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               key_value TEXT NOT NULL UNIQUE,
                                               request_hash TEXT NOT NULL,
                                               created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS payment (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       idempotency_id BIGINT NOT NULL UNIQUE,
                                       gateway_payment_id TEXT NOT NULL UNIQUE,
                                       amount_minor BIGINT NOT NULL,
                                       currency TEXT NOT NULL,
                                       status TEXT NOT NULL,
                                       order_id TEXT NOT NULL,
                                       created_at TIMESTAMP NOT NULL,
                                       metadata TEXT,
                                       message TEXT,
                                       FOREIGN KEY (idempotency_id) REFERENCES idempotency_key(id)
    );
